# Generated by Django 4.1.7 on 2023-02-27 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_seats_car_space_car_weight_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_id', models.UUIDField(default=0)),
                ('date', models.DateField(default=0)),
                ('time', models.TimeField(default=0)),
                ('ordered_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
