# Generated by Django 4.1.7 on 2023-02-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_delete_order_alter_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
