# Generated by Django 4.1.7 on 2023-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='media'),
        ),
    ]
