# Generated by Django 4.1.7 on 2023-02-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('eamil', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
